[package]
name = "confit"
version = "0.2.0"
authors = ["Judson <nyarly@gmail.com>"]
edition = "2018"
license-file = "LICENSE.md"

[dependencies]
nom = '5'
chrono = '0.4'
clap = '2'
serde = { version = "^1.0", features = ['derive'] }
serde_json = "^1.0"
anyhow = "^1.0"
